// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qiwezdgmupzdqrdmeabt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFpd2V6ZGdtdXB6ZHFyZG1lYWJ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzODM3ODQsImV4cCI6MjA3MTk1OTc4NH0.9Zc1dXwF_nOiwQmfAx3YOzoz79Sc74vNQ1tJC9zsW-A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});